kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "build-msa-dev-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: "node('agent') {\nstage 'build'\nopenshiftBuild(namespace: 'msa-dev',buildConfig: 'personneapi', showBuildLogs: 'true')\nstage 'deploy'\nopenshiftDeploy(namespace: 'msa-dev',deploymentConfig: 'personneapi')\n}"
